apiVersion: app/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    name: orders-deployment
    app: micro-shop
spec:
  selector:
    matchLabels:
      name: orders-pod
      app: micro-shop
  replicas: 1
  template:
    metadata:
      name: orders-pod
      labels:
        name: orders-pod
        app: micro-shop
    restartPolicy: Always
    containers:
      - name: orders
        image: order:latest
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: 128mi
            cpu: 500M
        env:
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: orders-configmap
                key: DATABASE_USER_cfg
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: orders-configmap
                key: DATABASE_NAME_cfg
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orders-secret
                key: DATABASE_PASSWORD_srt
